name: Build and Deploy
on:
  schedule:
      - cron: '30 23 * * *'
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: pip install requests
    - run: python wx.py

    - name: Build and deploy with gh-pages
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_REPOSITORY: wx
